displayName: MxM OWASP CRS Modsecurity Plugin
type: middleware

import: github.com/madebymode/traefik-modsecurity-plugin

summary: 'Traefik plugin to proxy requests through owasp/modsecurity-crs'

testData:
  ModsecurityUrl: http://waf:80
  TimeoutMillis: 2000
  JailEnabled: true

iconPath: ./img/icon.png
bannerPath: ./img/banner.png
